"""Backfill sequence_counters from existing order/invoice/ticket numbers.

Migration 0026 created sequence_counters empty. Any order, invoice, or
support ticket numbers generated by the old COUNT(...)-then-format scheme
before 0026 was deployed are invisible to the new atomic counter, so the
first real request after cutover re-generates the same number and hits the
unique constraint (seen in production: duplicate key "HDH-202607-000001").

This seeds each key's last_value to the max sequence already used for its
prefix, so next_sequence_value() resumes after the highest existing number
instead of restarting at 1.

Revision ID: 0033_backfill_sequence_counters
Revises: 0032_product_image_large_url_and_version
Create Date: 2026-07-07
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0033_backfill_sequence_counters"
down_revision: str | None = "0032_product_image_large_url_and_version"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("""
        INSERT INTO sequence_counters (key, last_value)
        SELECT 'order_number:' || substring(order_number FROM 1 FOR 11),
               MAX(CAST(substring(order_number FROM 12) AS INTEGER))
        FROM orders
        WHERE order_number ~ '^HDH-\\d{6}-\\d{6}$'
        GROUP BY substring(order_number FROM 1 FOR 11)
        ON CONFLICT (key) DO UPDATE
        SET last_value = GREATEST(sequence_counters.last_value, EXCLUDED.last_value)
        """)
    op.execute("""
        INSERT INTO sequence_counters (key, last_value)
        SELECT 'invoice_number:' || substring(invoice_number FROM 1 FOR 11),
               MAX(CAST(substring(invoice_number FROM 12) AS INTEGER))
        FROM invoices
        WHERE invoice_number ~ '^INV-\\d{6}-\\d{6}$'
        GROUP BY substring(invoice_number FROM 1 FOR 11)
        ON CONFLICT (key) DO UPDATE
        SET last_value = GREATEST(sequence_counters.last_value, EXCLUDED.last_value)
        """)
    op.execute("""
        INSERT INTO sequence_counters (key, last_value)
        SELECT 'ticket_number:' || substring(ticket_number FROM 5 FOR 4),
               MAX(CAST(substring(ticket_number FROM 10) AS INTEGER))
        FROM support_tickets
        WHERE ticket_number ~ '^SUP-\\d{4}-\\d{4}$'
        GROUP BY substring(ticket_number FROM 5 FOR 4)
        ON CONFLICT (key) DO UPDATE
        SET last_value = GREATEST(sequence_counters.last_value, EXCLUDED.last_value)
        """)


def downgrade() -> None:
    # No-op: this migration only raises last_value floors to match existing
    # data. Reverting could allow already-issued numbers to be reused.
    pass
