"""Premium notification templates — upgrade every default template to the new
design system and add the missing order-lifecycle templates.

Content comes from `app.modules.notifications.emails.catalog` (the single
source of truth for default template HTML, generated by the email design
system in `emails/components.py`). Importing app code into a migration is a
deliberate trade-off here: inlining ~17 full HTML documents would duplicate
the design system and drift immediately. The migration is idempotent — rows
whose content already matches the catalog are skipped.

Backward compatibility:
- Existing rows are UPDATEd only after their current content is snapshotted
  into `notification_template_versions` (same mechanism the admin Template
  Editor uses), so any previous version can be restored from the admin UI.
- Rows are never deleted. New templates are INSERTed with version 1.
- `notification_rules` for the new event types (order_confirmed,
  order_processing, order_packed, order_return_requested, order_returned) are
  created by `sync_notification_rules()` at app startup — no rule seeding here.

Revision ID: 0051_premium_notification_templates
Revises: 0050_financial_integrity_constraints
Create Date: 2026-07-15
"""

from __future__ import annotations

import json
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.modules.notifications.emails.catalog import ALL_TEMPLATES

revision: str = "0051_premium_notification_templates"
down_revision: str | None = "0050_financial_integrity_constraints"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Template names that did not exist before this migration (safe to delete on
# downgrade). Everything else is an in-place upgrade of an existing default.
_NEW_TEMPLATE_NAMES = [
    "order_confirmed_email",
    "order_processing_email",
    "order_packed_email",
    "order_return_requested_email",
    "order_returned_email",
    "order_packed_whatsapp",
]


def upgrade() -> None:
    conn = op.get_bind()

    for tpl in ALL_TEMPLATES:
        variables_json = (
            json.dumps(tpl.variables) if tpl.variables is not None else None
        )
        row = (
            conn.execute(
                sa.text(
                    "SELECT id, subject, template_body, variables, version "
                    "FROM notification_templates WHERE name = :name"
                ),
                {"name": tpl.name},
            )
            .mappings()
            .first()
        )

        if row is None:
            conn.execute(
                sa.text(
                    "INSERT INTO notification_templates "
                    "(name, channel, event_type, subject, template_body, "
                    "variables, is_active, version) "
                    "VALUES (:name, :channel, :event_type, :subject, :body, "
                    "CAST(:variables AS JSONB), TRUE, 1) "
                    "ON CONFLICT (name) DO NOTHING"
                ),
                {
                    "name": tpl.name,
                    "channel": tpl.channel,
                    "event_type": tpl.event_type,
                    "subject": tpl.subject,
                    "body": tpl.body,
                    "variables": variables_json,
                },
            )
            continue

        unchanged = (
            row["template_body"] == tpl.body
            and row["subject"] == tpl.subject
            and (row["variables"] or None) == (tpl.variables or None)
        )
        if unchanged:
            continue

        # Snapshot the current content so admins can restore it, then upgrade.
        conn.execute(
            sa.text(
                "INSERT INTO notification_template_versions "
                "(template_id, version, subject, template_body, variables) "
                "VALUES (:template_id, :version, :subject, :body, "
                "CAST(:variables AS JSONB)) "
                "ON CONFLICT (template_id, version) DO NOTHING"
            ),
            {
                "template_id": row["id"],
                "version": row["version"],
                "subject": row["subject"],
                "body": row["template_body"],
                "variables": (
                    json.dumps(row["variables"])
                    if row["variables"] is not None
                    else None
                ),
            },
        )
        conn.execute(
            sa.text(
                "UPDATE notification_templates "
                "SET subject = :subject, template_body = :body, "
                "variables = CAST(:variables AS JSONB), "
                "version = version + 1, updated_at = NOW() "
                "WHERE id = :id"
            ),
            {
                "id": row["id"],
                "subject": tpl.subject,
                "body": tpl.body,
                "variables": variables_json,
            },
        )


def downgrade() -> None:
    conn = op.get_bind()

    # Remove templates introduced by this migration.
    conn.execute(
        sa.text("DELETE FROM notification_templates WHERE name = ANY(:names)"),
        {"names": _NEW_TEMPLATE_NAMES},
    )

    # Restore upgraded templates from the snapshot taken in upgrade() —
    # best-effort: the most recent snapshot below the current version.
    upgraded = [t.name for t in ALL_TEMPLATES if t.name not in _NEW_TEMPLATE_NAMES]
    for name in upgraded:
        row = (
            conn.execute(
                sa.text(
                    "SELECT id, version FROM notification_templates "
                    "WHERE name = :name"
                ),
                {"name": name},
            )
            .mappings()
            .first()
        )
        if row is None:
            continue
        snap = (
            conn.execute(
                sa.text(
                    "SELECT version, subject, template_body, variables "
                    "FROM notification_template_versions "
                    "WHERE template_id = :tid AND version < :v "
                    "ORDER BY version DESC LIMIT 1"
                ),
                {"tid": row["id"], "v": row["version"]},
            )
            .mappings()
            .first()
        )
        if snap is None:
            continue
        conn.execute(
            sa.text(
                "UPDATE notification_templates "
                "SET subject = :subject, template_body = :body, "
                "variables = CAST(:variables AS JSONB), version = :version, "
                "updated_at = NOW() WHERE id = :id"
            ),
            {
                "id": row["id"],
                "subject": snap["subject"],
                "body": snap["template_body"],
                "variables": (
                    json.dumps(snap["variables"])
                    if snap["variables"] is not None
                    else None
                ),
                "version": snap["version"],
            },
        )
