/**
 * Crop Preset Registry — TS mirror of PRESET_REGISTRY in
 * Backend/app/modules/media/preset_registry.py. The frontend never
 * hardcodes preset shape/aspect/variant logic; it reads this table (or, once
 * Phase 2 wires GET /admin/media/presets, the live backend copy) instead.
 *
 * See docs/architecture/Universal_Responsive_Image_System_Design.md §5-§6.
 */

import type { CropPreset } from "./media";

function res(width: number, height: number) {
  return { width, height };
}

const defaultRotation = (allowed: CropPreset["rotation"]["allowed"]) => ({
  allowed,
  minDegrees: -180,
  maxDegrees: 180,
  stepDegrees: 1,
});

const jpegPngWebp = (folder: string, maxFileMb: number, strictBounds = false) => ({
  folder,
  maxFileMb,
  allowedMime: ["image/jpeg", "image/png", "image/webp"],
  strictBounds,
});

export const PRESET_REGISTRY: Record<string, CropPreset> = {
  product: {
    id: "product",
    label: "Product",
    shape: "square",
    maskSvg: null,
    aspectRatio: { desktop: 1, tablet: 1, mobile: 1 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { desktop: res(800, 800), tablet: res(800, 800), mobile: res(800, 800) },
    maxZoom: 5,
    rotation: defaultRotation("free"),
    breakpoints: ["desktop", "tablet", "mobile"],
    outputVariants: [
      { name: "thumbnail", width: 200, height: 200, dprs: [1, 2], format: "webp" },
      { name: "medium", width: 600, height: 600, dprs: [1, 2], format: "webp" },
      { name: "large", width: 1200, height: 1200, dprs: [1, 2], format: "webp" },
    ],
    storageRules: jpegPngWebp("products/", 10, true),
    referenceUi: "product-card",
  },
  collection: {
    id: "collection",
    label: "Collection",
    shape: "square",
    maskSvg: null,
    aspectRatio: { desktop: 1, mobile: 1 },
    safeArea: { top: 0, right: 0, bottom: 20, left: 0 },
    minResolution: { desktop: res(1200, 1200), mobile: res(600, 600) },
    maxZoom: 4,
    rotation: defaultRotation("none"),
    breakpoints: ["desktop", "mobile"],
    outputVariants: [
      { name: "thumbnail", width: 200, height: 200, dprs: [1], format: "webp" },
      { name: "medium", width: 600, height: 600, dprs: [1], format: "webp" },
      { name: "large", width: 1200, height: 1200, dprs: [1], format: "webp" },
    ],
    storageRules: jpegPngWebp("collections/", 10),
    referenceUi: "collection-tile",
  },
  category: {
    id: "category",
    label: "Category",
    shape: "square",
    maskSvg: null,
    aspectRatio: { desktop: 1, mobile: 1 },
    safeArea: { top: 0, right: 0, bottom: 20, left: 0 },
    minResolution: { desktop: res(1200, 1200), mobile: res(600, 600) },
    maxZoom: 4,
    rotation: defaultRotation("none"),
    breakpoints: ["desktop", "mobile"],
    outputVariants: [
      { name: "thumbnail", width: 200, height: 200, dprs: [1], format: "webp" },
      { name: "medium", width: 600, height: 600, dprs: [1], format: "webp" },
      { name: "large", width: 1200, height: 1200, dprs: [1], format: "webp" },
    ],
    storageRules: jpegPngWebp("categories/", 10),
    referenceUi: "category-tile",
  },
  // Split into two single-breakpoint presets — the CMS Hero Carousel editor
  // uploads and crops the desktop and mobile hero images as two entirely
  // independent images (often different source photos), each with its own
  // upload button and single-frame crop, not one image cropped two ways.
  hero_desktop: {
    id: "hero_desktop",
    label: "Hero — Desktop",
    shape: "rectangle",
    maskSvg: null,
    aspectRatio: { desktop: 1920 / 700 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 45 },
    minResolution: { desktop: res(1920, 700) },
    maxZoom: 3,
    rotation: defaultRotation("none"),
    breakpoints: ["desktop"],
    outputVariants: [{ name: "hero-desktop", width: 1920, height: 700, dprs: [1, 2], format: "webp" }],
    storageRules: jpegPngWebp("hero/", 15, true),
    referenceUi: "hero-full-bleed",
  },
  hero_mobile: {
    id: "hero_mobile",
    label: "Hero — Mobile",
    shape: "rectangle",
    maskSvg: null,
    aspectRatio: { mobile: 390 / 600 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { mobile: res(390, 600) },
    maxZoom: 3,
    rotation: defaultRotation("none"),
    breakpoints: ["mobile"],
    outputVariants: [{ name: "hero-mobile", width: 390, height: 600, dprs: [1, 2], format: "webp" }],
    storageRules: jpegPngWebp("hero/", 15, true),
    referenceUi: "hero-full-bleed",
  },
  promo_banner: {
    id: "promo_banner",
    label: "Promo Banner",
    shape: "rectangle",
    maskSvg: null,
    aspectRatio: { desktop: 1920 / 720, mobile: 750 / 1000 },
    safeArea: { top: 0, right: 40, bottom: 25, left: 0 },
    minResolution: { desktop: res(1920, 720), mobile: res(750, 1000) },
    maxZoom: 3,
    rotation: defaultRotation("none"),
    breakpoints: ["desktop", "mobile"],
    outputVariants: [{ name: "banner", width: 1920, height: 720, dprs: [1, 2], format: "webp" }],
    storageRules: jpegPngWebp("banners/", 15),
    referenceUi: "promo-banner",
  },
  gender_section: {
    id: "gender_section",
    label: "Gender Section",
    shape: "circle",
    maskSvg: null,
    aspectRatio: { desktop: 1, mobile: 1 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { desktop: res(600, 600), mobile: res(400, 400) },
    maxZoom: 4,
    rotation: defaultRotation("none"),
    breakpoints: ["desktop", "mobile"],
    outputVariants: [
      { name: "thumb", width: 200, height: 200, dprs: [1], format: "webp" },
      { name: "medium", width: 500, height: 500, dprs: [1], format: "webp" },
    ],
    storageRules: jpegPngWebp("gender-section/", 8),
    referenceUi: "gender-circle",
  },
  testimonial_avatar: {
    id: "testimonial_avatar",
    label: "Testimonial Avatar",
    shape: "circle",
    maskSvg: null,
    aspectRatio: { all: 1 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { all: res(300, 300) },
    maxZoom: 5,
    rotation: defaultRotation("none"),
    breakpoints: ["all"],
    outputVariants: [{ name: "avatar", width: 200, height: 200, dprs: [1], format: "webp" }],
    storageRules: jpegPngWebp("testimonials/", 5),
    referenceUi: "testimonial-avatar",
  },
  instagram_tile: {
    id: "instagram_tile",
    label: "Instagram Gallery",
    shape: "square",
    maskSvg: null,
    aspectRatio: { desktop: 1, mobile: 1 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { desktop: res(500, 500), mobile: res(500, 500) },
    maxZoom: 3,
    rotation: defaultRotation("none"),
    breakpoints: ["desktop", "mobile"],
    outputVariants: [
      { name: "thumb", width: 250, height: 250, dprs: [1], format: "webp" },
      { name: "medium", width: 500, height: 500, dprs: [1], format: "webp" },
    ],
    storageRules: jpegPngWebp("instagram/", 10),
    referenceUi: "instagram-tile",
  },
  footer_logo: {
    id: "footer_logo",
    label: "Footer Logo",
    shape: "contain",
    maskSvg: null,
    aspectRatio: { all: null },
    safeArea: { top: 10, right: 10, bottom: 10, left: 10 },
    minResolution: { all: res(300, 100) },
    maxZoom: 1,
    rotation: defaultRotation("none"),
    breakpoints: ["all"],
    outputVariants: [
      { name: "web", width: 400, height: 0, dprs: [1], format: "webp" },
      { name: "print", width: 1200, height: 0, dprs: [1], format: "png" },
    ],
    storageRules: {
      folder: "branding/",
      maxFileMb: 5,
      allowedMime: ["image/png", "image/svg+xml", "image/webp"],
      strictBounds: false,
    },
    referenceUi: "footer-logo",
  },
  company_logo: {
    id: "company_logo",
    label: "Company Logo",
    shape: "contain",
    maskSvg: null,
    aspectRatio: { all: null },
    safeArea: { top: 10, right: 10, bottom: 10, left: 10 },
    minResolution: { all: res(300, 100) },
    maxZoom: 1,
    rotation: defaultRotation("none"),
    breakpoints: ["all"],
    outputVariants: [
      { name: "web", width: 400, height: 0, dprs: [1], format: "webp" },
      { name: "print", width: 1200, height: 0, dprs: [1], format: "png" },
    ],
    storageRules: {
      folder: "branding/",
      maxFileMb: 5,
      allowedMime: ["image/png", "image/svg+xml", "image/webp"],
      strictBounds: false,
    },
    referenceUi: "company-logo",
  },
  seo_og: {
    id: "seo_og",
    label: "SEO / OpenGraph Image",
    shape: "rectangle",
    maskSvg: null,
    aspectRatio: { all: 1200 / 630 },
    safeArea: { top: 8, right: 8, bottom: 8, left: 8 },
    minResolution: { all: res(1200, 630) },
    maxZoom: 3,
    rotation: defaultRotation("none"),
    breakpoints: ["all"],
    outputVariants: [{ name: "og", width: 1200, height: 630, dprs: [1], format: "webp" }],
    storageRules: jpegPngWebp("seo/", 5),
    referenceUi: "seo-og",
  },
  avatar: {
    id: "avatar",
    label: "Avatar",
    shape: "circle",
    maskSvg: null,
    aspectRatio: { all: 1 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { all: res(200, 200) },
    maxZoom: 5,
    rotation: defaultRotation("none"),
    breakpoints: ["all"],
    outputVariants: [
      { name: "avatar", width: 400, height: 400, dprs: [1], format: "webp" },
      { name: "avatar-sm", width: 100, height: 100, dprs: [1], format: "webp" },
    ],
    storageRules: jpegPngWebp("avatars/", 5),
    referenceUi: "avatar",
  },
  review_photo: {
    id: "review_photo",
    label: "Review Photo",
    shape: "contain",
    maskSvg: null,
    aspectRatio: { all: null },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { all: res(400, 300) },
    maxZoom: 1,
    rotation: defaultRotation("none"),
    breakpoints: ["all"],
    outputVariants: [
      { name: "thumb", width: 150, height: 150, dprs: [1], format: "webp" },
      { name: "medium", width: 600, height: 450, dprs: [1], format: "webp" },
    ],
    storageRules: jpegPngWebp("reviews/", 8),
    referenceUi: "review-photo",
  },
  team_member: {
    id: "team_member",
    label: "Team Member",
    shape: "circle",
    maskSvg: null,
    aspectRatio: { all: 1 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { all: res(400, 400) },
    maxZoom: 4,
    rotation: defaultRotation("none"),
    breakpoints: ["all"],
    outputVariants: [{ name: "portrait", width: 400, height: 400, dprs: [1], format: "webp" }],
    storageRules: jpegPngWebp("team/", 8),
    referenceUi: "team-member",
  },
  blog_cover: {
    id: "blog_cover",
    label: "Blog Cover",
    shape: "rectangle",
    maskSvg: null,
    aspectRatio: { desktop: 1600 / 900, mobile: 750 / 900 },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { desktop: res(1600, 900), mobile: res(750, 900) },
    maxZoom: 3,
    rotation: defaultRotation("none"),
    breakpoints: ["desktop", "mobile"],
    outputVariants: [{ name: "cover", width: 1600, height: 900, dprs: [1, 2], format: "webp" }],
    storageRules: jpegPngWebp("blog/", 12),
    referenceUi: "blog-cover",
  },
  blog_inline: {
    id: "blog_inline",
    label: "Blog Inline Image",
    shape: "contain",
    maskSvg: null,
    aspectRatio: { all: null },
    safeArea: { top: 0, right: 0, bottom: 0, left: 0 },
    minResolution: { all: res(400, 300) },
    maxZoom: 1,
    rotation: defaultRotation("none"),
    breakpoints: ["all"],
    outputVariants: [{ name: "inline", width: 1200, height: 0, dprs: [1], format: "webp" }],
    storageRules: jpegPngWebp("blog/", 12),
    referenceUi: "blog-inline",
  },
};

export function getPreset(presetId: string): CropPreset {
  const preset = PRESET_REGISTRY[presetId];
  if (!preset) {
    throw new Error(`Unknown crop preset: ${presetId}`);
  }
  return preset;
}
