/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as Admin2faRouteImport } from './routes/admin.2fa'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminNotificationsIndexRouteImport } from './routes/admin.notifications.index'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin.collections.index'
import { Route as AdminCmsIndexRouteImport } from './routes/admin.cms.index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin.categories.index'
import { Route as AdminSettingsSecurityRouteImport } from './routes/admin.settings.security'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin.products.$productId'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminNotificationsTemplatesRouteImport } from './routes/admin.notifications.templates'
import { Route as AdminNotificationsProvidersRouteImport } from './routes/admin.notifications.providers'
import { Route as AdminNotificationsMatrixRouteImport } from './routes/admin.notifications.matrix'
import { Route as AdminNotificationsLogsRouteImport } from './routes/admin.notifications.logs'
import { Route as AdminNotificationsAnalyticsRouteImport } from './routes/admin.notifications.analytics'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin.collections.new'
import { Route as AdminCollectionsCollectionIdRouteImport } from './routes/admin.collections.$collectionId'
import { Route as AdminCmsMediaRouteImport } from './routes/admin.cms.media'
import { Route as AdminCmsSectionKeyRouteImport } from './routes/admin.cms.$sectionKey'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin.categories.new'
import { Route as AdminCategoriesCategoryIdRouteImport } from './routes/admin.categories.$categoryId'
import { Route as AdminNotificationsTemplatesIndexRouteImport } from './routes/admin.notifications.templates.index'
import { Route as AdminCollectionsCollectionIdIndexRouteImport } from './routes/admin.collections.$collectionId.index'
import { Route as AdminCategoriesCategoryIdIndexRouteImport } from './routes/admin.categories.$categoryId.index'
import { Route as AdminNotificationsTemplatesTemplateIdRouteImport } from './routes/admin.notifications.templates.$templateId'
import { Route as AdminCollectionsCollectionIdEditRouteImport } from './routes/admin.collections.$collectionId.edit'
import { Route as AdminCategoriesCategoryIdEditRouteImport } from './routes/admin.categories.$categoryId.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const Admin2faRoute = Admin2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminNotificationsIndexRoute = AdminNotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNotificationsRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCollectionsRoute,
} as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminSettingsSecurityRoute = AdminSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminNotificationsTemplatesRoute =
  AdminNotificationsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AdminNotificationsRoute,
  } as any)
const AdminNotificationsProvidersRoute =
  AdminNotificationsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AdminNotificationsRoute,
  } as any)
const AdminNotificationsMatrixRoute =
  AdminNotificationsMatrixRouteImport.update({
    id: '/matrix',
    path: '/matrix',
    getParentRoute: () => AdminNotificationsRoute,
  } as any)
const AdminNotificationsLogsRoute = AdminNotificationsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminNotificationsRoute,
} as any)
const AdminNotificationsAnalyticsRoute =
  AdminNotificationsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminNotificationsRoute,
  } as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCollectionsRoute,
} as any)
const AdminCollectionsCollectionIdRoute =
  AdminCollectionsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => AdminCollectionsRoute,
  } as any)
const AdminCmsMediaRoute = AdminCmsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsSectionKeyRoute = AdminCmsSectionKeyRouteImport.update({
  id: '/$sectionKey',
  path: '/$sectionKey',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminCategoriesCategoryIdRoute =
  AdminCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => AdminCategoriesRoute,
  } as any)
const AdminNotificationsTemplatesIndexRoute =
  AdminNotificationsTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminNotificationsTemplatesRoute,
  } as any)
const AdminCollectionsCollectionIdIndexRoute =
  AdminCollectionsCollectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCollectionsCollectionIdRoute,
  } as any)
const AdminCategoriesCategoryIdIndexRoute =
  AdminCategoriesCategoryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCategoriesCategoryIdRoute,
  } as any)
const AdminNotificationsTemplatesTemplateIdRoute =
  AdminNotificationsTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AdminNotificationsTemplatesRoute,
  } as any)
const AdminCollectionsCollectionIdEditRoute =
  AdminCollectionsCollectionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminCollectionsCollectionIdRoute,
  } as any)
const AdminCategoriesCategoryIdEditRoute =
  AdminCategoriesCategoryIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminCategoriesCategoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/2fa': typeof Admin2faRoute
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdRouteWithChildren
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/cms/$sectionKey': typeof AdminCmsSectionKeyRoute
  '/admin/cms/media': typeof AdminCmsMediaRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRouteWithChildren
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/notifications/analytics': typeof AdminNotificationsAnalyticsRoute
  '/admin/notifications/logs': typeof AdminNotificationsLogsRoute
  '/admin/notifications/matrix': typeof AdminNotificationsMatrixRoute
  '/admin/notifications/providers': typeof AdminNotificationsProvidersRoute
  '/admin/notifications/templates': typeof AdminNotificationsTemplatesRouteWithChildren
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/notifications/templates/$templateId': typeof AdminNotificationsTemplatesTemplateIdRoute
  '/admin/categories/$categoryId/': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/collections/$collectionId/': typeof AdminCollectionsCollectionIdIndexRoute
  '/admin/notifications/templates/': typeof AdminNotificationsTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/2fa': typeof Admin2faRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/cms/$sectionKey': typeof AdminCmsSectionKeyRoute
  '/admin/cms/media': typeof AdminCmsMediaRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/notifications/analytics': typeof AdminNotificationsAnalyticsRoute
  '/admin/notifications/logs': typeof AdminNotificationsLogsRoute
  '/admin/notifications/matrix': typeof AdminNotificationsMatrixRoute
  '/admin/notifications/providers': typeof AdminNotificationsProvidersRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/notifications/templates/$templateId': typeof AdminNotificationsTemplatesTemplateIdRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdIndexRoute
  '/admin/notifications/templates': typeof AdminNotificationsTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/2fa': typeof Admin2faRoute
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdRouteWithChildren
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/cms/$sectionKey': typeof AdminCmsSectionKeyRoute
  '/admin/cms/media': typeof AdminCmsMediaRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRouteWithChildren
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/notifications/analytics': typeof AdminNotificationsAnalyticsRoute
  '/admin/notifications/logs': typeof AdminNotificationsLogsRoute
  '/admin/notifications/matrix': typeof AdminNotificationsMatrixRoute
  '/admin/notifications/providers': typeof AdminNotificationsProvidersRoute
  '/admin/notifications/templates': typeof AdminNotificationsTemplatesRouteWithChildren
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/security': typeof AdminSettingsSecurityRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/notifications/templates/$templateId': typeof AdminNotificationsTemplatesTemplateIdRoute
  '/admin/categories/$categoryId/': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/collections/$collectionId/': typeof AdminCollectionsCollectionIdIndexRoute
  '/admin/notifications/templates/': typeof AdminNotificationsTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/2fa'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/'
    | '/admin/categories/$categoryId'
    | '/admin/categories/new'
    | '/admin/cms/$sectionKey'
    | '/admin/cms/media'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/notifications/analytics'
    | '/admin/notifications/logs'
    | '/admin/notifications/matrix'
    | '/admin/notifications/providers'
    | '/admin/notifications/templates'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/settings/security'
    | '/admin/categories/'
    | '/admin/cms/'
    | '/admin/collections/'
    | '/admin/notifications/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/notifications/templates/$templateId'
    | '/admin/categories/$categoryId/'
    | '/admin/collections/$collectionId/'
    | '/admin/notifications/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/2fa'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/templates'
    | '/admin'
    | '/admin/categories/new'
    | '/admin/cms/$sectionKey'
    | '/admin/cms/media'
    | '/admin/collections/new'
    | '/admin/notifications/analytics'
    | '/admin/notifications/logs'
    | '/admin/notifications/matrix'
    | '/admin/notifications/providers'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/settings/security'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/notifications/templates/$templateId'
    | '/admin/categories/$categoryId'
    | '/admin/collections/$collectionId'
    | '/admin/notifications/templates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/2fa'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/enquiries'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/'
    | '/admin/categories/$categoryId'
    | '/admin/categories/new'
    | '/admin/cms/$sectionKey'
    | '/admin/cms/media'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/notifications/analytics'
    | '/admin/notifications/logs'
    | '/admin/notifications/matrix'
    | '/admin/notifications/providers'
    | '/admin/notifications/templates'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/settings/security'
    | '/admin/categories/'
    | '/admin/cms/'
    | '/admin/collections/'
    | '/admin/notifications/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/notifications/templates/$templateId'
    | '/admin/categories/$categoryId/'
    | '/admin/collections/$collectionId/'
    | '/admin/notifications/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/2fa': {
      id: '/admin/2fa'
      path: '/2fa'
      fullPath: '/admin/2fa'
      preLoaderRoute: typeof Admin2faRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/notifications/': {
      id: '/admin/notifications/'
      path: '/'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AdminNotificationsIndexRouteImport
      parentRoute: typeof AdminNotificationsRoute
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/settings/security': {
      id: '/admin/settings/security'
      path: '/security'
      fullPath: '/admin/settings/security'
      preLoaderRoute: typeof AdminSettingsSecurityRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/notifications/templates': {
      id: '/admin/notifications/templates'
      path: '/templates'
      fullPath: '/admin/notifications/templates'
      preLoaderRoute: typeof AdminNotificationsTemplatesRouteImport
      parentRoute: typeof AdminNotificationsRoute
    }
    '/admin/notifications/providers': {
      id: '/admin/notifications/providers'
      path: '/providers'
      fullPath: '/admin/notifications/providers'
      preLoaderRoute: typeof AdminNotificationsProvidersRouteImport
      parentRoute: typeof AdminNotificationsRoute
    }
    '/admin/notifications/matrix': {
      id: '/admin/notifications/matrix'
      path: '/matrix'
      fullPath: '/admin/notifications/matrix'
      preLoaderRoute: typeof AdminNotificationsMatrixRouteImport
      parentRoute: typeof AdminNotificationsRoute
    }
    '/admin/notifications/logs': {
      id: '/admin/notifications/logs'
      path: '/logs'
      fullPath: '/admin/notifications/logs'
      preLoaderRoute: typeof AdminNotificationsLogsRouteImport
      parentRoute: typeof AdminNotificationsRoute
    }
    '/admin/notifications/analytics': {
      id: '/admin/notifications/analytics'
      path: '/analytics'
      fullPath: '/admin/notifications/analytics'
      preLoaderRoute: typeof AdminNotificationsAnalyticsRouteImport
      parentRoute: typeof AdminNotificationsRoute
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/collections/$collectionId': {
      id: '/admin/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/admin/collections/$collectionId'
      preLoaderRoute: typeof AdminCollectionsCollectionIdRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/cms/media': {
      id: '/admin/cms/media'
      path: '/media'
      fullPath: '/admin/cms/media'
      preLoaderRoute: typeof AdminCmsMediaRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/$sectionKey': {
      id: '/admin/cms/$sectionKey'
      path: '/$sectionKey'
      fullPath: '/admin/cms/$sectionKey'
      preLoaderRoute: typeof AdminCmsSectionKeyRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/categories/$categoryId': {
      id: '/admin/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AdminCategoriesCategoryIdRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/notifications/templates/': {
      id: '/admin/notifications/templates/'
      path: '/'
      fullPath: '/admin/notifications/templates/'
      preLoaderRoute: typeof AdminNotificationsTemplatesIndexRouteImport
      parentRoute: typeof AdminNotificationsTemplatesRoute
    }
    '/admin/collections/$collectionId/': {
      id: '/admin/collections/$collectionId/'
      path: '/'
      fullPath: '/admin/collections/$collectionId/'
      preLoaderRoute: typeof AdminCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof AdminCollectionsCollectionIdRoute
    }
    '/admin/categories/$categoryId/': {
      id: '/admin/categories/$categoryId/'
      path: '/'
      fullPath: '/admin/categories/$categoryId/'
      preLoaderRoute: typeof AdminCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AdminCategoriesCategoryIdRoute
    }
    '/admin/notifications/templates/$templateId': {
      id: '/admin/notifications/templates/$templateId'
      path: '/$templateId'
      fullPath: '/admin/notifications/templates/$templateId'
      preLoaderRoute: typeof AdminNotificationsTemplatesTemplateIdRouteImport
      parentRoute: typeof AdminNotificationsTemplatesRoute
    }
    '/admin/collections/$collectionId/edit': {
      id: '/admin/collections/$collectionId/edit'
      path: '/edit'
      fullPath: '/admin/collections/$collectionId/edit'
      preLoaderRoute: typeof AdminCollectionsCollectionIdEditRouteImport
      parentRoute: typeof AdminCollectionsCollectionIdRoute
    }
    '/admin/categories/$categoryId/edit': {
      id: '/admin/categories/$categoryId/edit'
      path: '/edit'
      fullPath: '/admin/categories/$categoryId/edit'
      preLoaderRoute: typeof AdminCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AdminCategoriesCategoryIdRoute
    }
  }
}

interface AdminCategoriesCategoryIdRouteChildren {
  AdminCategoriesCategoryIdEditRoute: typeof AdminCategoriesCategoryIdEditRoute
  AdminCategoriesCategoryIdIndexRoute: typeof AdminCategoriesCategoryIdIndexRoute
}

const AdminCategoriesCategoryIdRouteChildren: AdminCategoriesCategoryIdRouteChildren =
  {
    AdminCategoriesCategoryIdEditRoute: AdminCategoriesCategoryIdEditRoute,
    AdminCategoriesCategoryIdIndexRoute: AdminCategoriesCategoryIdIndexRoute,
  }

const AdminCategoriesCategoryIdRouteWithChildren =
  AdminCategoriesCategoryIdRoute._addFileChildren(
    AdminCategoriesCategoryIdRouteChildren,
  )

interface AdminCategoriesRouteChildren {
  AdminCategoriesCategoryIdRoute: typeof AdminCategoriesCategoryIdRouteWithChildren
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
}

const AdminCategoriesRouteChildren: AdminCategoriesRouteChildren = {
  AdminCategoriesCategoryIdRoute: AdminCategoriesCategoryIdRouteWithChildren,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
}

const AdminCategoriesRouteWithChildren = AdminCategoriesRoute._addFileChildren(
  AdminCategoriesRouteChildren,
)

interface AdminCmsRouteChildren {
  AdminCmsSectionKeyRoute: typeof AdminCmsSectionKeyRoute
  AdminCmsMediaRoute: typeof AdminCmsMediaRoute
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsSectionKeyRoute: AdminCmsSectionKeyRoute,
  AdminCmsMediaRoute: AdminCmsMediaRoute,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

interface AdminCollectionsCollectionIdRouteChildren {
  AdminCollectionsCollectionIdEditRoute: typeof AdminCollectionsCollectionIdEditRoute
  AdminCollectionsCollectionIdIndexRoute: typeof AdminCollectionsCollectionIdIndexRoute
}

const AdminCollectionsCollectionIdRouteChildren: AdminCollectionsCollectionIdRouteChildren =
  {
    AdminCollectionsCollectionIdEditRoute:
      AdminCollectionsCollectionIdEditRoute,
    AdminCollectionsCollectionIdIndexRoute:
      AdminCollectionsCollectionIdIndexRoute,
  }

const AdminCollectionsCollectionIdRouteWithChildren =
  AdminCollectionsCollectionIdRoute._addFileChildren(
    AdminCollectionsCollectionIdRouteChildren,
  )

interface AdminCollectionsRouteChildren {
  AdminCollectionsCollectionIdRoute: typeof AdminCollectionsCollectionIdRouteWithChildren
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
}

const AdminCollectionsRouteChildren: AdminCollectionsRouteChildren = {
  AdminCollectionsCollectionIdRoute:
    AdminCollectionsCollectionIdRouteWithChildren,
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
}

const AdminCollectionsRouteWithChildren =
  AdminCollectionsRoute._addFileChildren(AdminCollectionsRouteChildren)

interface AdminNotificationsTemplatesRouteChildren {
  AdminNotificationsTemplatesTemplateIdRoute: typeof AdminNotificationsTemplatesTemplateIdRoute
  AdminNotificationsTemplatesIndexRoute: typeof AdminNotificationsTemplatesIndexRoute
}

const AdminNotificationsTemplatesRouteChildren: AdminNotificationsTemplatesRouteChildren =
  {
    AdminNotificationsTemplatesTemplateIdRoute:
      AdminNotificationsTemplatesTemplateIdRoute,
    AdminNotificationsTemplatesIndexRoute:
      AdminNotificationsTemplatesIndexRoute,
  }

const AdminNotificationsTemplatesRouteWithChildren =
  AdminNotificationsTemplatesRoute._addFileChildren(
    AdminNotificationsTemplatesRouteChildren,
  )

interface AdminNotificationsRouteChildren {
  AdminNotificationsAnalyticsRoute: typeof AdminNotificationsAnalyticsRoute
  AdminNotificationsLogsRoute: typeof AdminNotificationsLogsRoute
  AdminNotificationsMatrixRoute: typeof AdminNotificationsMatrixRoute
  AdminNotificationsProvidersRoute: typeof AdminNotificationsProvidersRoute
  AdminNotificationsTemplatesRoute: typeof AdminNotificationsTemplatesRouteWithChildren
  AdminNotificationsIndexRoute: typeof AdminNotificationsIndexRoute
}

const AdminNotificationsRouteChildren: AdminNotificationsRouteChildren = {
  AdminNotificationsAnalyticsRoute: AdminNotificationsAnalyticsRoute,
  AdminNotificationsLogsRoute: AdminNotificationsLogsRoute,
  AdminNotificationsMatrixRoute: AdminNotificationsMatrixRoute,
  AdminNotificationsProvidersRoute: AdminNotificationsProvidersRoute,
  AdminNotificationsTemplatesRoute:
    AdminNotificationsTemplatesRouteWithChildren,
  AdminNotificationsIndexRoute: AdminNotificationsIndexRoute,
}

const AdminNotificationsRouteWithChildren =
  AdminNotificationsRoute._addFileChildren(AdminNotificationsRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminSettingsRouteChildren {
  AdminSettingsSecurityRoute: typeof AdminSettingsSecurityRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsSecurityRoute: AdminSettingsSecurityRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  Admin2faRoute: typeof Admin2faRoute
  AdminCategoriesRoute: typeof AdminCategoriesRouteWithChildren
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  AdminCollectionsRoute: typeof AdminCollectionsRouteWithChildren
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  Admin2faRoute: Admin2faRoute,
  AdminCategoriesRoute: AdminCategoriesRouteWithChildren,
  AdminCmsRoute: AdminCmsRouteWithChildren,
  AdminCollectionsRoute: AdminCollectionsRouteWithChildren,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
