from enum import StrEnum


class ResponseCode(StrEnum):
    # ── Auth ─────────────────────────────────────────────────────────────────
    AUTH_TOKEN_VERIFIED = "AUTH_TOKEN_VERIFIED"
    AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"
    AUTH_FORCE_LOGOUT_SUCCESS = "AUTH_FORCE_LOGOUT_SUCCESS"
    AUTH_2FA_SETUP = "AUTH_2FA_SETUP"
    AUTH_2FA_VERIFIED = "AUTH_2FA_VERIFIED"
    AUTH_2FA_VALID = "AUTH_2FA_VALID"

    # ── Users / Profiles ─────────────────────────────────────────────────────
    USER_PROFILE_FETCHED = "USER_PROFILE_FETCHED"
    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED"
    USER_AVATAR_UPDATED = "USER_AVATAR_UPDATED"
    USER_LISTED = "USER_LISTED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_STATUS_CHANGED = "USER_STATUS_CHANGED"

    # ── Addresses ────────────────────────────────────────────────────────────
    ADDRESS_LISTED = "ADDRESS_LISTED"
    ADDRESS_CREATED = "ADDRESS_CREATED"
    ADDRESS_UPDATED = "ADDRESS_UPDATED"
    ADDRESS_DELETED = "ADDRESS_DELETED"
    ADDRESS_DEFAULT_SET = "ADDRESS_DEFAULT_SET"

    # ── Products ─────────────────────────────────────────────────────────────
    PRODUCT_LISTED = "PRODUCT_LISTED"
    PRODUCT_FETCHED = "PRODUCT_FETCHED"
    PRODUCT_CREATED = "PRODUCT_CREATED"
    PRODUCT_UPDATED = "PRODUCT_UPDATED"
    PRODUCT_DELETED = "PRODUCT_DELETED"
    PRODUCT_VARIANT_CREATED = "PRODUCT_VARIANT_CREATED"
    PRODUCT_VARIANT_UPDATED = "PRODUCT_VARIANT_UPDATED"
    PRODUCT_VARIANT_DELETED = "PRODUCT_VARIANT_DELETED"
    PRODUCT_ATTRIBUTE_UPSERTED = "PRODUCT_ATTRIBUTE_UPSERTED"
    PRODUCT_ATTRIBUTE_DELETED = "PRODUCT_ATTRIBUTE_DELETED"
    PRODUCT_STOCK_ADJUSTED = "PRODUCT_STOCK_ADJUSTED"
    PRODUCT_IMAGE_UPLOADED = "PRODUCT_IMAGE_UPLOADED"
    PRODUCT_IMAGE_DELETED = "PRODUCT_IMAGE_DELETED"
    PRODUCT_IMAGE_PRIMARY_SET = "PRODUCT_IMAGE_PRIMARY_SET"

    # ── Categories ───────────────────────────────────────────────────────────
    CATEGORY_LISTED = "CATEGORY_LISTED"
    CATEGORY_CREATED = "CATEGORY_CREATED"
    CATEGORY_UPDATED = "CATEGORY_UPDATED"
    CATEGORY_DELETED = "CATEGORY_DELETED"

    # ── Collections ──────────────────────────────────────────────────────────
    COLLECTION_LISTED = "COLLECTION_LISTED"
    COLLECTION_FETCHED = "COLLECTION_FETCHED"
    COLLECTION_CREATED = "COLLECTION_CREATED"
    COLLECTION_UPDATED = "COLLECTION_UPDATED"
    COLLECTION_DELETED = "COLLECTION_DELETED"
    COLLECTION_PRODUCTS_ADDED = "COLLECTION_PRODUCTS_ADDED"
    COLLECTION_PRODUCT_REMOVED = "COLLECTION_PRODUCT_REMOVED"

    # ── Cart ─────────────────────────────────────────────────────────────────
    CART_FETCHED = "CART_FETCHED"
    CART_ITEM_ADDED = "CART_ITEM_ADDED"
    CART_ITEM_UPDATED = "CART_ITEM_UPDATED"
    CART_ITEM_REMOVED = "CART_ITEM_REMOVED"
    CART_CLEARED = "CART_CLEARED"
    CART_MERGED = "CART_MERGED"

    # ── Wishlist ─────────────────────────────────────────────────────────────
    WISHLIST_FETCHED = "WISHLIST_FETCHED"
    WISHLIST_ITEM_ADDED = "WISHLIST_ITEM_ADDED"
    WISHLIST_ITEM_REMOVED = "WISHLIST_ITEM_REMOVED"
    WISHLIST_TOGGLED = "WISHLIST_TOGGLED"

    # ── Orders ───────────────────────────────────────────────────────────────
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_LISTED = "ORDER_LISTED"
    ORDER_FETCHED = "ORDER_FETCHED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_STATUS_UPDATED = "ORDER_STATUS_UPDATED"

    # ── Payments ─────────────────────────────────────────────────────────────
    PAYMENT_ORDER_CREATED = "PAYMENT_ORDER_CREATED"
    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    PAYMENT_FETCHED = "PAYMENT_FETCHED"
    REFUND_INITIATED = "REFUND_INITIATED"
    REFUND_LISTED = "REFUND_LISTED"

    # ── Coupons ──────────────────────────────────────────────────────────────
    COUPON_VALIDATED = "COUPON_VALIDATED"
    COUPON_LISTED = "COUPON_LISTED"
    COUPON_CREATED = "COUPON_CREATED"
    COUPON_UPDATED = "COUPON_UPDATED"
    COUPON_DELETED = "COUPON_DELETED"

    # ── Reviews ──────────────────────────────────────────────────────────────
    REVIEW_LISTED = "REVIEW_LISTED"
    REVIEW_SUMMARY_FETCHED = "REVIEW_SUMMARY_FETCHED"
    REVIEW_SUBMITTED = "REVIEW_SUBMITTED"
    REVIEW_UPDATED = "REVIEW_UPDATED"
    REVIEW_DELETED = "REVIEW_DELETED"
    REVIEW_VOTED = "REVIEW_VOTED"
    REVIEW_PENDING_LISTED = "REVIEW_PENDING_LISTED"
    REVIEW_ALL_LISTED = "REVIEW_ALL_LISTED"
    REVIEW_ACTION_APPLIED = "REVIEW_ACTION_APPLIED"

    # ── CMS ──────────────────────────────────────────────────────────────────
    CMS_HOME_FETCHED = "CMS_HOME_FETCHED"
    CMS_HOMEPAGE_FETCHED = "CMS_HOMEPAGE_FETCHED"
    CMS_PAGE_FETCHED = "CMS_PAGE_FETCHED"
    CMS_BANNER_LISTED = "CMS_BANNER_LISTED"
    CMS_BANNER_CREATED = "CMS_BANNER_CREATED"
    CMS_BANNER_UPDATED = "CMS_BANNER_UPDATED"
    CMS_BANNER_DELETED = "CMS_BANNER_DELETED"
    CMS_SECTION_LISTED = "CMS_SECTION_LISTED"
    CMS_SECTION_FETCHED = "CMS_SECTION_FETCHED"
    CMS_SECTION_UPDATED = "CMS_SECTION_UPDATED"
    CMS_SECTION_PUBLISHED = "CMS_SECTION_PUBLISHED"
    CMS_SECTION_TOGGLED = "CMS_SECTION_TOGGLED"
    CMS_DRAFT_SAVED = "CMS_DRAFT_SAVED"
    CMS_SECTIONS_REORDERED = "CMS_SECTIONS_REORDERED"
    CMS_PAGE_CREATED = "CMS_PAGE_CREATED"
    CMS_PAGE_UPDATED = "CMS_PAGE_UPDATED"
    CMS_ITEM_CREATED = "CMS_ITEM_CREATED"
    CMS_ITEM_UPDATED = "CMS_ITEM_UPDATED"
    CMS_ITEM_DELETED = "CMS_ITEM_DELETED"
    CMS_ITEMS_LISTED = "CMS_ITEMS_LISTED"
    CMS_ITEMS_REORDERED = "CMS_ITEMS_REORDERED"
    CMS_VERSION_LISTED = "CMS_VERSION_LISTED"
    CMS_VERSION_ROLLED_BACK = "CMS_VERSION_ROLLED_BACK"
    CMS_CACHE_INVALIDATED = "CMS_CACHE_INVALIDATED"
    CMS_MEDIA_LISTED = "CMS_MEDIA_LISTED"
    CMS_MEDIA_UPLOADED = "CMS_MEDIA_UPLOADED"
    CMS_MEDIA_UPDATED = "CMS_MEDIA_UPDATED"
    CMS_MEDIA_DELETED = "CMS_MEDIA_DELETED"
    CMS_PUBLISH_LOG_LISTED = "CMS_PUBLISH_LOG_LISTED"

    # ── Notifications ────────────────────────────────────────────────────────
    NOTIFICATION_PREFERENCES_FETCHED = "NOTIFICATION_PREFERENCES_FETCHED"
    NOTIFICATION_PREFERENCE_UPSERTED = "NOTIFICATION_PREFERENCE_UPSERTED"
    NOTIFICATION_LOGS_LISTED = "NOTIFICATION_LOGS_LISTED"

    # ── Reports / Analytics ──────────────────────────────────────────────────
    ANALYTICS_EVENT_TRACKED = "ANALYTICS_EVENT_TRACKED"
    ANALYTICS_DASHBOARD_FETCHED = "ANALYTICS_DASHBOARD_FETCHED"

    # ── Shipping ─────────────────────────────────────────────────────────────
    SHIPMENT_FETCHED = "SHIPMENT_FETCHED"
    SHIPMENT_TRACKED = "SHIPMENT_TRACKED"
    SHIPPING_RATES_FETCHED = "SHIPPING_RATES_FETCHED"
    SHIPMENT_CREATED = "SHIPMENT_CREATED"
    SHIPMENT_UPDATED = "SHIPMENT_UPDATED"
    SHIPMENT_CANCELLED = "SHIPMENT_CANCELLED"

    # ── Inventory ────────────────────────────────────────────────────────────
    INVENTORY_LOW_STOCK_LISTED = "INVENTORY_LOW_STOCK_LISTED"
    INVENTORY_HISTORY_FETCHED = "INVENTORY_HISTORY_FETCHED"
    INVENTORY_ADJUSTED = "INVENTORY_ADJUSTED"
    INVENTORY_SUMMARY_FETCHED = "INVENTORY_SUMMARY_FETCHED"
    INVENTORY_RESERVATIONS_LISTED = "INVENTORY_RESERVATIONS_LISTED"
    INVENTORY_TRANSACTIONS_LISTED = "INVENTORY_TRANSACTIONS_LISTED"
    INVENTORY_ALERTS_CHECKED = "INVENTORY_ALERTS_CHECKED"

    # ── Reviews / Notifications admin actions ─────────────────────────────────
    REVIEW_REMINDERS_SENT = "REVIEW_REMINDERS_SENT"
    NOTIFICATIONS_RETRIED = "NOTIFICATIONS_RETRIED"

    # ── Support ──────────────────────────────────────────────────────────────
    SUPPORT_TICKET_CREATED = "SUPPORT_TICKET_CREATED"
    SUPPORT_TICKET_LISTED = "SUPPORT_TICKET_LISTED"
    SUPPORT_TICKET_FETCHED = "SUPPORT_TICKET_FETCHED"
    SUPPORT_TICKET_REPLIED = "SUPPORT_TICKET_REPLIED"
    SUPPORT_TICKET_UPDATED = "SUPPORT_TICKET_UPDATED"

    # ── Returns ──────────────────────────────────────────────────────────────
    RETURN_CREATED = "RETURN_CREATED"
    RETURN_LISTED = "RETURN_LISTED"
    RETURN_STATUS_UPDATED = "RETURN_STATUS_UPDATED"

    # ── Search ───────────────────────────────────────────────────────────────
    SEARCH_RESULTS_FETCHED = "SEARCH_RESULTS_FETCHED"
    SEARCH_AUTOCOMPLETE_FETCHED = "SEARCH_AUTOCOMPLETE_FETCHED"
    SEARCH_TRENDING_FETCHED = "SEARCH_TRENDING_FETCHED"

    # ── SEO ──────────────────────────────────────────────────────────────────
    SEO_PAGE_FETCHED = "SEO_PAGE_FETCHED"
    SEO_PAGE_UPSERTED = "SEO_PAGE_UPSERTED"
    SEO_REDIRECT_CREATED = "SEO_REDIRECT_CREATED"

    # ── Admin ────────────────────────────────────────────────────────────────
    ADMIN_DASHBOARD_FETCHED = "ADMIN_DASHBOARD_FETCHED"
    ADMIN_AUDIT_LOGS_FETCHED = "ADMIN_AUDIT_LOGS_FETCHED"

    # ── Fraud ────────────────────────────────────────────────────────────────
    FRAUD_SIGNALS_LISTED = "FRAUD_SIGNALS_LISTED"
    FRAUD_SIGNAL_CREATED = "FRAUD_SIGNAL_CREATED"
    FRAUD_SIGNAL_RESOLVED = "FRAUD_SIGNAL_RESOLVED"

    # ── Settings ─────────────────────────────────────────────────────────────
    SETTINGS_FLAGS_LISTED = "SETTINGS_FLAGS_LISTED"
    SETTINGS_FLAG_UPDATED = "SETTINGS_FLAG_UPDATED"

    # ── Media ────────────────────────────────────────────────────────────────
    MEDIA_IMAGE_UPLOADED = "MEDIA_IMAGE_UPLOADED"
    MEDIA_IMAGE_DELETED = "MEDIA_IMAGE_DELETED"
    MEDIA_PRIMARY_SET = "MEDIA_PRIMARY_SET"
    MEDIA_IMAGE_CROPPED = "MEDIA_IMAGE_CROPPED"
    MEDIA_IMAGE_REPLACED = "MEDIA_IMAGE_REPLACED"

    # ── Universal Image System ──────────────────────────────────────────────
    UNIVERSAL_PRESETS_LISTED = "UNIVERSAL_PRESETS_LISTED"
    UNIVERSAL_IMAGE_UPLOADED = "UNIVERSAL_IMAGE_UPLOADED"
    UNIVERSAL_IMAGE_CROPPED = "UNIVERSAL_IMAGE_CROPPED"
    UNIVERSAL_IMAGE_REPLACED = "UNIVERSAL_IMAGE_REPLACED"
    UNIVERSAL_IMAGE_ATTACHED = "UNIVERSAL_IMAGE_ATTACHED"
    UNIVERSAL_IMAGE_SET_PRIMARY = "UNIVERSAL_IMAGE_SET_PRIMARY"
    UNIVERSAL_IMAGES_REORDERED = "UNIVERSAL_IMAGES_REORDERED"
    UNIVERSAL_IMAGE_DELETED = "UNIVERSAL_IMAGE_DELETED"
    UNIVERSAL_VARIANTS_REGENERATED = "UNIVERSAL_VARIANTS_REGENERATED"

    # ── Invoices ─────────────────────────────────────────────────────────────
    INVOICE_DOWNLOAD_READY = "INVOICE_DOWNLOAD_READY"

    # ── Webhooks ─────────────────────────────────────────────────────────────
    WEBHOOK_PROCESSED = "WEBHOOK_PROCESSED"

    # ── Company Config ───────────────────────────────────────────────────────
    COMPANY_CONFIG_RETRIEVED = "COMPANY_CONFIG_RETRIEVED"
    COMPANY_CONFIG_UPDATED = "COMPANY_CONFIG_UPDATED"

    # ── Dev Auth (development only) ───────────────────────────────────────────
    DEV_AUTH_LOGIN = "DEV_AUTH_LOGIN"
    DEV_AUTH_ME = "DEV_AUTH_ME"
