/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoreLocatorRouteImport } from './routes/store-locator'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout_.success'
import { Route as CheckoutStockChangedRouteImport } from './routes/checkout_.stock-changed'
import { Route as CheckoutReservationExpiredRouteImport } from './routes/checkout_.reservation-expired'
import { Route as CheckoutPaymentFailedRouteImport } from './routes/checkout_.payment-failed'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AccountResetPasswordRouteImport } from './routes/account.reset-password'
import { Route as AccountRegisterRouteImport } from './routes/account.register'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountForgotPasswordRouteImport } from './routes/account.forgot-password'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin.collections.index'
import { Route as AdminCmsIndexRouteImport } from './routes/admin.cms.index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin.categories.index'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin.products.$productId'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin.collections.new'
import { Route as AdminCollectionsCollectionIdRouteImport } from './routes/admin.collections.$collectionId'
import { Route as AdminCmsMediaRouteImport } from './routes/admin.cms.media'
import { Route as AdminCmsSectionKeyRouteImport } from './routes/admin.cms.$sectionKey'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin.categories.new'
import { Route as AdminCategoriesCategoryIdRouteImport } from './routes/admin.categories.$categoryId'
import { Route as AdminCollectionsCollectionIdIndexRouteImport } from './routes/admin.collections.$collectionId.index'
import { Route as AdminCategoriesCategoryIdIndexRouteImport } from './routes/admin.categories.$categoryId.index'
import { Route as AdminCollectionsCollectionIdEditRouteImport } from './routes/admin.collections.$collectionId.edit'
import { Route as AdminCategoriesCategoryIdEditRouteImport } from './routes/admin.categories.$categoryId.edit'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLocatorRoute = StoreLocatorRouteImport.update({
  id: '/store-locator',
  path: '/store-locator',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout_/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutStockChangedRoute = CheckoutStockChangedRouteImport.update({
  id: '/checkout_/stock-changed',
  path: '/checkout/stock-changed',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReservationExpiredRoute =
  CheckoutReservationExpiredRouteImport.update({
    id: '/checkout_/reservation-expired',
    path: '/checkout/reservation-expired',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutPaymentFailedRoute = CheckoutPaymentFailedRouteImport.update({
  id: '/checkout_/payment-failed',
  path: '/checkout/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/account/reset-password',
  path: '/account/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCollectionsRoute,
} as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCollectionsRoute,
} as any)
const AdminCollectionsCollectionIdRoute =
  AdminCollectionsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => AdminCollectionsRoute,
  } as any)
const AdminCmsMediaRoute = AdminCmsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsSectionKeyRoute = AdminCmsSectionKeyRouteImport.update({
  id: '/$sectionKey',
  path: '/$sectionKey',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminCategoriesCategoryIdRoute =
  AdminCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => AdminCategoriesRoute,
  } as any)
const AdminCollectionsCollectionIdIndexRoute =
  AdminCollectionsCollectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCollectionsCollectionIdRoute,
  } as any)
const AdminCategoriesCategoryIdIndexRoute =
  AdminCategoriesCategoryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCategoriesCategoryIdRoute,
  } as any)
const AdminCollectionsCollectionIdEditRoute =
  AdminCollectionsCollectionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminCollectionsCollectionIdRoute,
  } as any)
const AdminCategoriesCategoryIdEditRoute =
  AdminCategoriesCategoryIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminCategoriesCategoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/store-locator': typeof StoreLocatorRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/checkout/payment-failed': typeof CheckoutPaymentFailedRoute
  '/checkout/reservation-expired': typeof CheckoutReservationExpiredRoute
  '/checkout/stock-changed': typeof CheckoutStockChangedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdRouteWithChildren
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/cms/$sectionKey': typeof AdminCmsSectionKeyRoute
  '/admin/cms/media': typeof AdminCmsMediaRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRouteWithChildren
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/categories/$categoryId/': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/collections/$collectionId/': typeof AdminCollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/store-locator': typeof StoreLocatorRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/checkout/payment-failed': typeof CheckoutPaymentFailedRoute
  '/checkout/reservation-expired': typeof CheckoutReservationExpiredRoute
  '/checkout/stock-changed': typeof CheckoutStockChangedRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/cms/$sectionKey': typeof AdminCmsSectionKeyRoute
  '/admin/cms/media': typeof AdminCmsMediaRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/store-locator': typeof StoreLocatorRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/checkout_/payment-failed': typeof CheckoutPaymentFailedRoute
  '/checkout_/reservation-expired': typeof CheckoutReservationExpiredRoute
  '/checkout_/stock-changed': typeof CheckoutStockChangedRoute
  '/checkout_/success': typeof CheckoutSuccessRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/categories/$categoryId': typeof AdminCategoriesCategoryIdRouteWithChildren
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/cms/$sectionKey': typeof AdminCmsSectionKeyRoute
  '/admin/cms/media': typeof AdminCmsMediaRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRouteWithChildren
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/categories/$categoryId/edit': typeof AdminCategoriesCategoryIdEditRoute
  '/admin/collections/$collectionId/edit': typeof AdminCollectionsCollectionIdEditRoute
  '/admin/categories/$categoryId/': typeof AdminCategoriesCategoryIdIndexRoute
  '/admin/collections/$collectionId/': typeof AdminCollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/shipping-returns'
    | '/store-locator'
    | '/terms'
    | '/wishlist'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/checkout/payment-failed'
    | '/checkout/reservation-expired'
    | '/checkout/stock-changed'
    | '/checkout/success'
    | '/collections/$slug'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/collections/'
    | '/products/'
    | '/admin/categories/$categoryId'
    | '/admin/categories/new'
    | '/admin/cms/$sectionKey'
    | '/admin/cms/media'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/categories/'
    | '/admin/cms/'
    | '/admin/collections/'
    | '/admin/products/'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/categories/$categoryId/'
    | '/admin/collections/$collectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/shipping-returns'
    | '/store-locator'
    | '/terms'
    | '/wishlist'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/reviews'
    | '/checkout/payment-failed'
    | '/checkout/reservation-expired'
    | '/checkout/stock-changed'
    | '/checkout/success'
    | '/collections/$slug'
    | '/products/$slug'
    | '/account'
    | '/admin'
    | '/collections'
    | '/products'
    | '/admin/categories/new'
    | '/admin/cms/$sectionKey'
    | '/admin/cms/media'
    | '/admin/collections/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/products'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/categories/$categoryId'
    | '/admin/collections/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/shipping-returns'
    | '/store-locator'
    | '/terms'
    | '/wishlist'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/categories'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/checkout_/payment-failed'
    | '/checkout_/reservation-expired'
    | '/checkout_/stock-changed'
    | '/checkout_/success'
    | '/collections/$slug'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/collections/'
    | '/products/'
    | '/admin/categories/$categoryId'
    | '/admin/categories/new'
    | '/admin/cms/$sectionKey'
    | '/admin/cms/media'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/categories/'
    | '/admin/cms/'
    | '/admin/collections/'
    | '/admin/products/'
    | '/admin/categories/$categoryId/edit'
    | '/admin/collections/$collectionId/edit'
    | '/admin/categories/$categoryId/'
    | '/admin/collections/$collectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  StoreLocatorRoute: typeof StoreLocatorRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  CheckoutPaymentFailedRoute: typeof CheckoutPaymentFailedRoute
  CheckoutReservationExpiredRoute: typeof CheckoutReservationExpiredRoute
  CheckoutStockChangedRoute: typeof CheckoutStockChangedRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-locator': {
      id: '/store-locator'
      path: '/store-locator'
      fullPath: '/store-locator'
      preLoaderRoute: typeof StoreLocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/success': {
      id: '/checkout_/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/stock-changed': {
      id: '/checkout_/stock-changed'
      path: '/checkout/stock-changed'
      fullPath: '/checkout/stock-changed'
      preLoaderRoute: typeof CheckoutStockChangedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/reservation-expired': {
      id: '/checkout_/reservation-expired'
      path: '/checkout/reservation-expired'
      fullPath: '/checkout/reservation-expired'
      preLoaderRoute: typeof CheckoutReservationExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/payment-failed': {
      id: '/checkout_/payment-failed'
      path: '/checkout/payment-failed'
      fullPath: '/checkout/payment-failed'
      preLoaderRoute: typeof CheckoutPaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/collections/$collectionId': {
      id: '/admin/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/admin/collections/$collectionId'
      preLoaderRoute: typeof AdminCollectionsCollectionIdRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/cms/media': {
      id: '/admin/cms/media'
      path: '/media'
      fullPath: '/admin/cms/media'
      preLoaderRoute: typeof AdminCmsMediaRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/$sectionKey': {
      id: '/admin/cms/$sectionKey'
      path: '/$sectionKey'
      fullPath: '/admin/cms/$sectionKey'
      preLoaderRoute: typeof AdminCmsSectionKeyRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/categories/$categoryId': {
      id: '/admin/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/admin/categories/$categoryId'
      preLoaderRoute: typeof AdminCategoriesCategoryIdRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/collections/$collectionId/': {
      id: '/admin/collections/$collectionId/'
      path: '/'
      fullPath: '/admin/collections/$collectionId/'
      preLoaderRoute: typeof AdminCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof AdminCollectionsCollectionIdRoute
    }
    '/admin/categories/$categoryId/': {
      id: '/admin/categories/$categoryId/'
      path: '/'
      fullPath: '/admin/categories/$categoryId/'
      preLoaderRoute: typeof AdminCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AdminCategoriesCategoryIdRoute
    }
    '/admin/collections/$collectionId/edit': {
      id: '/admin/collections/$collectionId/edit'
      path: '/edit'
      fullPath: '/admin/collections/$collectionId/edit'
      preLoaderRoute: typeof AdminCollectionsCollectionIdEditRouteImport
      parentRoute: typeof AdminCollectionsCollectionIdRoute
    }
    '/admin/categories/$categoryId/edit': {
      id: '/admin/categories/$categoryId/edit'
      path: '/edit'
      fullPath: '/admin/categories/$categoryId/edit'
      preLoaderRoute: typeof AdminCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AdminCategoriesCategoryIdRoute
    }
  }
}

interface AdminCategoriesCategoryIdRouteChildren {
  AdminCategoriesCategoryIdEditRoute: typeof AdminCategoriesCategoryIdEditRoute
  AdminCategoriesCategoryIdIndexRoute: typeof AdminCategoriesCategoryIdIndexRoute
}

const AdminCategoriesCategoryIdRouteChildren: AdminCategoriesCategoryIdRouteChildren =
  {
    AdminCategoriesCategoryIdEditRoute: AdminCategoriesCategoryIdEditRoute,
    AdminCategoriesCategoryIdIndexRoute: AdminCategoriesCategoryIdIndexRoute,
  }

const AdminCategoriesCategoryIdRouteWithChildren =
  AdminCategoriesCategoryIdRoute._addFileChildren(
    AdminCategoriesCategoryIdRouteChildren,
  )

interface AdminCategoriesRouteChildren {
  AdminCategoriesCategoryIdRoute: typeof AdminCategoriesCategoryIdRouteWithChildren
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
}

const AdminCategoriesRouteChildren: AdminCategoriesRouteChildren = {
  AdminCategoriesCategoryIdRoute: AdminCategoriesCategoryIdRouteWithChildren,
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
}

const AdminCategoriesRouteWithChildren = AdminCategoriesRoute._addFileChildren(
  AdminCategoriesRouteChildren,
)

interface AdminCmsRouteChildren {
  AdminCmsSectionKeyRoute: typeof AdminCmsSectionKeyRoute
  AdminCmsMediaRoute: typeof AdminCmsMediaRoute
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsSectionKeyRoute: AdminCmsSectionKeyRoute,
  AdminCmsMediaRoute: AdminCmsMediaRoute,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

interface AdminCollectionsCollectionIdRouteChildren {
  AdminCollectionsCollectionIdEditRoute: typeof AdminCollectionsCollectionIdEditRoute
  AdminCollectionsCollectionIdIndexRoute: typeof AdminCollectionsCollectionIdIndexRoute
}

const AdminCollectionsCollectionIdRouteChildren: AdminCollectionsCollectionIdRouteChildren =
  {
    AdminCollectionsCollectionIdEditRoute:
      AdminCollectionsCollectionIdEditRoute,
    AdminCollectionsCollectionIdIndexRoute:
      AdminCollectionsCollectionIdIndexRoute,
  }

const AdminCollectionsCollectionIdRouteWithChildren =
  AdminCollectionsCollectionIdRoute._addFileChildren(
    AdminCollectionsCollectionIdRouteChildren,
  )

interface AdminCollectionsRouteChildren {
  AdminCollectionsCollectionIdRoute: typeof AdminCollectionsCollectionIdRouteWithChildren
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
}

const AdminCollectionsRouteChildren: AdminCollectionsRouteChildren = {
  AdminCollectionsCollectionIdRoute:
    AdminCollectionsCollectionIdRouteWithChildren,
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
}

const AdminCollectionsRouteWithChildren =
  AdminCollectionsRoute._addFileChildren(AdminCollectionsRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRouteWithChildren
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  AdminCollectionsRoute: typeof AdminCollectionsRouteWithChildren
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRouteWithChildren,
  AdminCmsRoute: AdminCmsRouteWithChildren,
  AdminCollectionsRoute: AdminCollectionsRouteWithChildren,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  StoreLocatorRoute: StoreLocatorRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  CheckoutPaymentFailedRoute: CheckoutPaymentFailedRoute,
  CheckoutReservationExpiredRoute: CheckoutReservationExpiredRoute,
  CheckoutStockChangedRoute: CheckoutStockChangedRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
