apiVersion: 1

policies:
  - orgId: 1
    name: hadha-critical
    receiver: admin-email
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    match:
      severity: critical
    continue: true

  - orgId: 1
    name: hadha-warning
    receiver: admin-email
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    match:
      severity: warning
    continue: true

  - orgId: 1
    name: hadha-info
    receiver: admin-email
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 0s
    match:
      severity: info

  - orgId: 1
    name: hadha-default
    receiver: admin-email
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
